# Generated by Django 6.0.7 on 2026-07-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customer_cart_order_customer_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('step', models.CharField(choices=[('idle', 'Inactif'), ('collect_products', 'Collecte produits'), ('customer_name', 'Nom client'), ('customer_email', 'Email client'), ('customer_phone', 'Téléphone client'), ('customer_address', 'Adresse client'), ('confirm', 'Confirmation')], default='idle', max_length=32)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('customer_address', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
